In [1]:
import pandas as pd

In [6]:
coal = pd.read_csv("../Underlying Data/Coal Futures Historical Data.csv", sep=',', header=0)

In [8]:
coal.head()

           Date  Price   Open   High    Low Vol. Change %
0  Mar 20, 2019  65.05  65.05  65.05  65.05    -    0.00%
1  Mar 19, 2019  65.05  65.05  65.05  65.05    -   -5.79%
2  Mar 18, 2019  69.05  69.05  69.05  69.05    -    0.00%
3  Mar 15, 2019  69.05  69.05  69.05  69.05    -    0.00%
4  Mar 14, 2019  69.05  69.05  69.05  69.05    -    0.00%

In [13]:
coal.index = pd.to_datetime(coal['Date'])

In [14]:
coal

                    Date  Price   Open   High    Low Vol. Change %
Date
2019-03-20  Mar 20, 2019  65.05  65.05  65.05  65.05    -    0.00%
2019-03-19  Mar 19, 2019  65.05  65.05  65.05  65.05    -   -5.79%
2019-03-18  Mar 18, 2019  69.05  69.05  69.05  69.05    -    0.00%
2019-03-15  Mar 15, 2019  69.05  69.05  69.05  69.05    -    0.00%
2019-03-14  Mar 14, 2019  69.05  69.05  69.05  69.05    -    0.00%
2019-03-13  Mar 13, 2019  69.05  69.05  69.05  69.05    -    0.00%
2019-03-12  Mar 12, 2019  69.05  69.05  69.05  69.05    -    0.00%
2019-03-11  Mar 11, 2019  69.05  69.05  69.05  69.05    -    0.00%
2019-03-08  Mar 08, 2019  69.05  69.05  69.05  69.05    -   -0.36%
2019-03-07  Mar 07, 2019  69.30  69.30  69.30  69.30    -    0.00%
2019-03-06  Mar 06, 2019  69.30  69.30  69.30  69.30    -   -1.07%
2019-03-05  Mar 05, 2019  70.05  70.05  70.05  70.05    -   -0.71%
2019-03-04  Mar 04, 2019  70.55  70.55  70.55  70.55    -    0.00%
2019-03-01  Mar 01, 2019  70.55  70.55  70.55  70.55    -   -0.35%
2019-02-28  Feb 28, 2019  70.80  70.80  70.80  70.80    -    0.00%
2019-02-27  Feb 27, 2019  70.80  70.80  70.80  70.80    -    0.00%
2019-02-26  Feb 26, 2019  70.80  70.80  70.80  70.80    -   -1.05%
2019-02-25  Feb 25, 2019  71.55  71.55  71.55  71.55    -    0.00%
2019-02-22  Feb 22, 2019  71.55  71.55  71.55  71.55    -   -2.05%
2019-02-21  Feb 21, 2019  73.05  73.05  73.05  73.05    -    0.00%
2019-02-20  Feb 20, 2019  73.05  73.05  73.05  73.05    -   -0.34%
2019-02-19  Feb 19, 2019  73.30  73.30  73.30  73.30    -   -0.68%
2019-02-18  Feb 18, 2019  73.80  73.80  73.80  73.80    -    0.00%
2019-02-15  Feb 15, 2019  73.80  73.80  73.80  73.80    -    0.00%
2019-02-14  Feb 14, 2019  73.80  73.80  73.80  73.80    -   -0.67%
2019-02-13  Feb 13, 2019  74.30  74.30  74.30  74.30    -   -0.34%
2019-02-12  Feb 12, 2019  74.55  74.55  74.55  74.55    -   -0.33%
2019-02-11  Feb 11, 2019  74.80  74.80  74.80  74.80    -   -0.33%
2019-02-08  Feb 08, 2019  75.05  75.05  75.05  75.05    -    0.00%
2019-02-07  Feb 07, 2019  75.05  75.05  75.05  75.05    -   -0.99%
...                  ...    ...    ...    ...    ...  ...      ...
2011-04-04  Apr 04, 2011  72.50  72.50  72.50  72.50    -    0.69%
2011-04-01  Apr 01, 2011  72.00  72.00  72.00  72.00    -   -1.37%
2011-03-31  Mar 31, 2011  73.00  73.00  73.00  73.00    -    1.18%
2011-03-30  Mar 30, 2011  72.15  72.15  72.15  72.15    -   -0.69%
2011-03-29  Mar 29, 2011  72.65  72.65  72.65  72.65    -   -0.82%
2011-03-28  Mar 28, 2011  73.25  73.25  73.25  73.25    -    3.90%
2011-03-25  Mar 25, 2011  70.50  70.50  70.50  70.50    -    3.68%
2011-03-24  Mar 24, 2011  68.00  68.00  68.00  68.00    -   -0.73%
2011-03-23  Mar 23, 2011  68.50  68.50  68.50  68.50    -   -0.72%
2011-03-22  Mar 22, 2011  69.00  69.00  69.00  69.00    -   -1.43%
2011-03-21  Mar 21, 2011  70.00  70.00  70.00  70.00    -   -1.75%
2011-03-18  Mar 18, 2011  71.25  71.25  71.25  71.25    -   -1.72%
2011-03-17  Mar 17, 2011  72.50  72.50  72.50  72.50    -    0.35%
2011-03-16  Mar 16, 2011  72.25  72.25  72.25  72.25    -    2.12%
2011-03-15  Mar 15, 2011  70.75  70.75  70.75  70.75    -    1.43%
2011-03-14  Mar 14, 2011  69.75  69.75  69.75  69.75    -    0.07%
2011-03-11  Mar 11, 2011  69.70  69.70  69.70  69.70    -    0.14%
2011-03-10  Mar 10, 2011  69.60  69.60  69.60  69.60    -   -0.14%
2011-03-09  Mar 09, 2011  69.70  69.70  69.70  69.70    -   -2.11%
2011-03-08  Mar 08, 2011  71.20  71.20  71.20  71.20    -    0.07%
2011-03-07  Mar 07, 2011  71.15  71.15  71.15  71.15    -    0.71%
2011-03-04  Mar 04, 2011  70.65  70.65  70.65  70.65    -   -0.42%
2011-03-03  Mar 03, 2011  70.95  70.95  70.95  70.95    -   -1.18%
2011-03-02  Mar 02, 2011  71.80  71.80  71.80  71.80    -    1.99%
2011-03-01  Mar 01, 2011  70.40  70.40  70.40  70.40    -    0.07%
2011-02-28  Feb 28, 2011  70.35  70.35  70.35  70.35    -    0.64%
2011-02-25  Feb 25, 2011  69.90  69.90  69.90  69.90    -   -0.50%
2011-02-24  Feb 24, 2011  70.25  70.25  70.25  70.25    -   -1.06%
2011-02-23  Feb 23, 2011  71.00  71.00  71.00  71.00    -    0.00%
2011-02-22  Feb 22, 2011  71.00  71.00  71.00  71.00    -    0.35%

[2071 rows x 7 columns]

In [17]:
coal_new = coal[['Price']]

In [21]:
coal_new.columns = ['Coal Futures']

coal_new

            Coal Futures
Date
2019-03-20         65.05
2019-03-19         65.05
2019-03-18         69.05
2019-03-15         69.05
2019-03-14         69.05
2019-03-13         69.05
2019-03-12         69.05
2019-03-11         69.05
2019-03-08         69.05
2019-03-07         69.30
2019-03-06         69.30
2019-03-05         70.05
2019-03-04         70.55
2019-03-01         70.55
2019-02-28         70.80
2019-02-27         70.80
2019-02-26         70.80
2019-02-25         71.55
2019-02-22         71.55
2019-02-21         73.05
2019-02-20         73.05
2019-02-19         73.30
2019-02-18         73.80
2019-02-15         73.80
2019-02-14         73.80
2019-02-13         74.30
2019-02-12         74.55
2019-02-11         74.80
2019-02-08         75.05
2019-02-07         75.05
...                  ...
2011-04-04         72.50
2011-04-01         72.00
2011-03-31         73.00
2011-03-30         72.15
2011-03-29         72.65
2011-03-28         73.25
2011-03-25         70.50
2011-03-24         68.00
2011-03-23         68.50
2011-03-22         69.00
2011-03-21         70.00
2011-03-18         71.25
2011-03-17         72.50
2011-03-16         72.25
2011-03-15         70.75
2011-03-14         69.75
2011-03-11         69.70
2011-03-10         69.60
2011-03-09         69.70
2011-03-08         71.20
2011-03-07         71.15
2011-03-04         70.65
2011-03-03         70.95
2011-03-02         71.80
2011-03-01         70.40
2011-02-28         70.35
2011-02-25         69.90
2011-02-24         70.25
2011-02-23         71.00
2011-02-22         71.00

[2071 rows x 1 columns]